services:
  - type: web
    name: raj-residency
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
